name: Nix
on:
  push:
    branches:
      - main
      - catalyst-fund*
  pull_request:

jobs:
  build-server:
    name: Build with Nix
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup
      uses: ./.github/actions/nix-common-setup
      with:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Flake check
      run: nix flake check

    - name: Build catalyst-toolbox
      run: nix build -L .#catalyst-toolbox

    - name: Build snapshot-lib
      run: nix build -L .#snapshot-lib
