name: Python scripts linters

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install linters
        run: pip3 install black

      - uses: actions/checkout@v3

      - name: Check formatting (black)
        run: black ./catalyst-toolbox/scripts/python --check
